// <auto-generated />
using System;
using CrossLoggerDataManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrossLoggerDataManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190318155502_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrossLoggerDataManager.Models.PersonalRecord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<int>("Weight");

                    b.HasKey("ID");

                    b.ToTable("PersonalRecords");
                });

            modelBuilder.Entity("CrossLoggerDataManager.Models.User", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CrossLoggerDataManager.Models.UserPersonalRecord", b =>
                {
                    b.Property<int>("PersonalRecordID");

                    b.Property<string>("UserID");

                    b.HasKey("PersonalRecordID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("UserPersonalRecords");
                });

            modelBuilder.Entity("CrossLoggerDataManager.Models.UserPersonalRecord", b =>
                {
                    b.HasOne("CrossLoggerDataManager.Models.PersonalRecord", "PersonalRecord")
                        .WithMany("UserPersonalRecords")
                        .HasForeignKey("PersonalRecordID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CrossLoggerDataManager.Models.User", "User")
                        .WithMany("UserPersonalRecords")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
